// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Google.ProtocolBuffers {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ProtobufMsgEnterGame {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      registry.Add(global::Google.ProtocolBuffers.ProtobufMsgEnterGame.MsgEnterGame);
    }
    #endregion
    #region Extensions
    public const int MsgEnterGameFieldNumber = 101;
    public static pb::GeneratedExtensionLite<global::Google.ProtocolBuffers.ServerMessage, global::Google.ProtocolBuffers.MsgEnterGame> MsgEnterGame;
    #endregion
    
    #region Static variables
    #endregion
    #region Extensions
    internal static readonly object Descriptor;
    static ProtobufMsgEnterGame() {
      Descriptor = null;
      global::Google.ProtocolBuffers.ProtobufMsgEnterGame.MsgEnterGame = 
        new pb::GeneratedExtensionLite<global::Google.ProtocolBuffers.ServerMessage, global::Google.ProtocolBuffers.MsgEnterGame>(
          "protobuf.msgEnterGame",
          global::Google.ProtocolBuffers.ServerMessage.DefaultInstance,
          null,
          global::Google.ProtocolBuffers.MsgEnterGame.DefaultInstance,
          null,
          global::Google.ProtocolBuffers.ProtobufMsgEnterGame.MsgEnterGameFieldNumber,
          pbd::FieldType.Message);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class MsgEnterGame : pb::GeneratedMessageLite<MsgEnterGame, MsgEnterGame.Builder> {
    private MsgEnterGame() { }
    private static readonly MsgEnterGame defaultInstance = new MsgEnterGame().MakeReadOnly();
    private static readonly string[] _msgEnterGameFieldNames = new string[] { "name", "serverId" };
    private static readonly uint[] _msgEnterGameFieldTags = new uint[] { 10, 16 };
    public static MsgEnterGame DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MsgEnterGame DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MsgEnterGame ThisMessage {
      get { return this; }
    }
    
    public const int NameFieldNumber = 1;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public const int ServerIdFieldNumber = 2;
    private bool hasServerId;
    private int serverId_;
    public bool HasServerId {
      get { return hasServerId; }
    }
    public int ServerId {
      get { return serverId_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _msgEnterGameFieldNames;
      if (hasName) {
        output.WriteString(1, field_names[0], Name);
      }
      if (hasServerId) {
        output.WriteInt32(2, field_names[1], ServerId);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasName) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Name);
        }
        if (hasServerId) {
          size += pb::CodedOutputStream.ComputeInt32Size(2, ServerId);
        }
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      if (hasName) hash ^= name_.GetHashCode();
      if (hasServerId) hash ^= serverId_.GetHashCode();
      return hash;
    }
    
    public override bool Equals(object obj) {
      MsgEnterGame other = obj as MsgEnterGame;
      if (other == null) return false;
      if (hasName != other.hasName || (hasName && !name_.Equals(other.name_))) return false;
      if (hasServerId != other.hasServerId || (hasServerId && !serverId_.Equals(other.serverId_))) return false;
      return true;
    }
    
    public override void PrintTo(global::System.IO.TextWriter writer) {
      PrintField("name", hasName, name_, writer);
      PrintField("serverId", hasServerId, serverId_, writer);
    }
    #endregion
    
    public static MsgEnterGame ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgEnterGame ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgEnterGame ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgEnterGame ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgEnterGame ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgEnterGame ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MsgEnterGame ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MsgEnterGame ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MsgEnterGame ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgEnterGame ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MsgEnterGame MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MsgEnterGame prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilderLite<MsgEnterGame, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MsgEnterGame cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MsgEnterGame result;
      
      private MsgEnterGame PrepareBuilder() {
        if (resultIsReadOnly) {
          MsgEnterGame original = result;
          result = new MsgEnterGame();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MsgEnterGame MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override MsgEnterGame DefaultInstanceForType {
        get { return global::Google.ProtocolBuffers.MsgEnterGame.DefaultInstance; }
      }
      
      public override MsgEnterGame BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessageLite other) {
        if (other is MsgEnterGame) {
          return MergeFrom((MsgEnterGame) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MsgEnterGame other) {
        if (other == global::Google.ProtocolBuffers.MsgEnterGame.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasName) {
          Name = other.Name;
        }
        if (other.HasServerId) {
          ServerId = other.ServerId;
        }
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_msgEnterGameFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _msgEnterGameFieldTags[field_ordinal];
            else {
              ParseUnknownField(input, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                return this;
              }
              ParseUnknownField(input, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasName = input.ReadString(ref result.name_);
              break;
            }
            case 16: {
              result.hasServerId = input.ReadInt32(ref result.serverId_);
              break;
            }
          }
        }
        
        return this;
      }
      
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      public bool HasServerId {
        get { return result.hasServerId; }
      }
      public int ServerId {
        get { return result.ServerId; }
        set { SetServerId(value); }
      }
      public Builder SetServerId(int value) {
        PrepareBuilder();
        result.hasServerId = true;
        result.serverId_ = value;
        return this;
      }
      public Builder ClearServerId() {
        PrepareBuilder();
        result.hasServerId = false;
        result.serverId_ = 0;
        return this;
      }
    }
    static MsgEnterGame() {
      object.ReferenceEquals(global::Google.ProtocolBuffers.ProtobufMsgEnterGame.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
